---
- name: Configure Spark environment
  template:
    src: spark-env.sh.j2
    dest: "{{ spark_conf_dir }}/conf/spark-env.sh"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"

- name: Configure Spark defaults config file
  template:
    src: spark-defaults.conf.j2
    dest: "{{ spark_conf_dir }}/conf/spark-defaults.conf"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
