---
- name: Ensure Spark log and run directories exist
  file:
    path: "{{ item }}"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
    mode: "0755"
    state: directory
  with_items:
    - "{{ spark_conf_dir }}"
    - "{{ spark_log_dir }}"

- name: Download Spark distribution
  get_url:
    url: "{{ spark_mirror }}/spark-{{ spark_version }}.tgz"
    dest: "{{ spark_src_dir }}/spark-{{ spark_version }}.tgz"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"

- name: Extract Spark distribution
  unarchive:
    src: "{{ spark_src_dir }}/spark-{{ spark_version }}.tgz"
    dest: "{{ spark_usr_parent_dir }}"
    copy: false
    creates: "{{ spark_usr_parent_dir }}/spark-{{ spark_version }}"
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"

- name: Setup Spark distribution symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: "{{ spark_user }}"
    group: "{{ spark_user }}"
  with_items:
    - { src: "{{ spark_usr_parent_dir }}/spark-{{ spark_version }}", dest: "{{ spark_usr_dir }}" }
    - { src: "{{ spark_usr_parent_dir }}/spark-{{ spark_version }}/conf", dest: "{{ spark_conf_dir }}/conf" }
